### ISSUE TITLE
Can't choose filename/directory for exports

### ISSUE THREAD

**Issue by vinegraft** [Jinjinov/OpenHabitTracker#1]
## Expected Behavior
OHT opens a dialog allowing you to choose the name and directory of export file. This is what happens when I use the web app version. My browser always asks me where to download files (which lets me choose the name as well). Or I could turn that feature off but still control the directory by changing default download location.

## Actual Behavior
OHT saves the export file to my ~/Downloads folder automatically with no choice for me to choose name or directory. I suspect this folder is used because I first ran the program from either ~/Downloads or ~/Downloads/OpenHabitTracker.Linux.1.0.3, I can't remember which.

## Steps to Reproduce the Problem
Click Export JSON/TSV/YAML/Markdown in the Backup menu.

## Specifications

  - Version: 1.0.3 Downloaded from the website
  - Platform: Linux Mint 21.3 Virginia

**Comment by Jinjinov** [comment]
Thank you for reporting this!

**Comment by Jinjinov** [comment]
This is by design.

The only library that supports Blazor on Linux is the Photino.Blazor library.

There is an open issue for native Linux file dialog: https://github.com/tryphotino/photino.Blazor/issues/76

Since this issues is still open, my solution was to trigger "file download" - that is why the file is saved in the Download folder.

**Comment by Jinjinov** [comment]
Can you try downloading version 1.0.7 from https://openhabittracker.net/ ?

Can you also try installing the snap version? https://snapcraft.io/openhabittracker

**Comment by Jinjinov** [comment]
All platforms, including Linux, now have platform native file dialogs:

For Linux:
https://github.com/Jinjinov/OpenHabitTracker/blob/main/OpenHabitTracker.Blazor.Photino/OpenFile.cs
https://github.com/Jinjinov/OpenHabitTracker/blob/main/OpenHabitTracker.Blazor.Photino/SaveFile.cs
