### ISSUE TITLE
Program hangs when opening, interface won't load

### ISSUE THREAD

**Issue by vinegraft** [Jinjinov/OpenHabitTracker#2]
## Expected Behavior
The interface loads when the program is run.
## Actual Behavior
A spinning exclamation marks logo spins forever and the interface never loads.

## Steps to Reproduce the Problem
Run the program.

## Specifications

  - Version: 1.0.5 and 1.0.6 Downloaded from the website
  - Platform: Linux Mint 21.3 Virginia

**Comment by Jinjinov** [comment]
Can you try installing `libwebkit2gtk-4.1` with

    sudo apt-get install libwebkit2gtk-4.1

and try again?

**Comment by vinegraft** [comment]
> Can you try installing `libwebkit2gtk-4.1` with
> 
> ```
> sudo apt-get install libwebkit2gtk-4.1
> ```
> 
> and try again?

I just tried this and the same problem persists, even after rebooting.

**Comment by Jinjinov** [comment]
Can you try downloading version 1.0.7 from https://openhabittracker.net/ ?

Can you also try installing the snap version? https://snapcraft.io/openhabittracker

**Comment by Jinjinov** [comment]
The problem with `libwebkit2gtk-4.1` has been solved, OpenHabitTracker now works on Linux.

It is needed by a NuGet https://github.com/tryphotino/photino.Blazor

Photino reverted to using `libwebkit2gtk-4.0` https://github.com/tryphotino/photino.Blazor/issues/134

When they upgrade to `libwebkit2gtk-4.1` again, I will update OpenHabitTracker.
