### ISSUE TITLE
System.IO.FileNotFoundException: The file zh.json does not exist.

### ISSUE THREAD

**Issue by pccai** [Jinjinov/OpenHabitTracker#3]
System.IO.FileNotFoundException: The file zh.json does not exist. at Microsoft.Extensions.FileProviders.NotFoundFileInfo.CreateReadStream() at OpenHabitTracker.Localization.JsonStringLocalizer.LoadStringMap() at OpenHabitTracker.Localization.JsonStringLocalizer.get_Item(String name) at Microsoft.Extensions.Localization.StringLocalizer`1.get_Item(String name) at OpenHabitTracker.Blazor.Layout.MainLayout.BuildRenderTree(RenderTreeBuilder __builder) at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder) at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

**Comment by Jinjinov** [comment]
Thank you for reporting this!

**Comment by Jinjinov** [comment]
The issue has been solved in OpenHabitTracker version 1.0.8
